<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

use Carbon\Carbon;

class OrdersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $start = Carbon::create("2020", "1", "1", "00", "00");
        $end = Carbon::create("2020", "12", "31", "00", "00");
        $min = strtotime($start);
        $max = strtotime($end);

        // 購入履歴登録
        DB::table('orders')->insert([
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1500,
                'payment_method' => '1',
                'users_id' => 1,
                'name' => 'James Riney',
                'furigana' => 'ジェームズ ライニー',
                'email' => 'james_riney@coralcap.co',
                'tel' => '000-0000-0001',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1500,
                'payment_method' => '1',
                'users_id' => 1,
                'name' => 'James Riney',
                'furigana' => 'ジェームズ ライニー',
                'email' => 'james_riney@coralcap.co',
                'tel' => '000-0000-0001',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 200,
                'total_amount' => 1700,
                'payment_method' => '1',
                'users_id' => 1,
                'name' => 'James Riney',
                'furigana' => 'ジェームズ ライニー',
                'email' => 'james_riney@coralcap.co',
                'tel' => '000-0000-0001',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1250,
                'payment_method' => '1',
                'users_id' => 2,
                'name' => '澤山 陽平',
                'furigana' => 'サワヤマ ヨウヘイ',
                'tel' => '000-0000-0002',
                'email' => 'sawayama@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 200,
                'total_amount' => 1450,
                'payment_method' => '1',
                'users_id' => 2,
                'name' => '澤山 陽平',
                'furigana' => 'サワヤマ ヨウヘイ',
                'tel' => '000-0000-0002',
                'email' => 'sawayama@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 100,
                'total_amount' => 1024,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '吉澤 美弥子',
                'furigana' => 'ヨシザワ ミサコ',
                'tel' => '000-0000-0003',
                'email' => 'yoshizawa@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1724,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '津田 遼',
                'furigana' => 'ツダ リョウ',
                'tel' => '000-0000-0004',
                'email' => 'tsuda@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 864,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '小林 恭子',
                'furigana' => 'コバヤシ キョウコ',
                'tel' => '000-0000-0005',
                'email' => 'kobayashi@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1024,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '西村 賢',
                'furigana' => 'ニシムラ ケン',
                'tel' => '000-0000-0006',
                'email' => 'nishimura@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 768,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '大森 貴之',
                'furigana' => 'オオモリ タカユキ',
                'tel' => '000-0000-0007',
                'email' => 'oomori@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 886,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '小林 翔太郎',
                'furigana' => 'コバヤシ ショウタロウ',
                'tel' => '000-0000-0008',
                'email' => 's_kobayashi@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1278,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '世古 圭',
                'furigana' => 'セコ ケイ',
                'tel' => '000-0000-0009',
                'email' => 'seko@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 947,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '井口 彰太',
                'furigana' => 'イグチ ショウタ',
                'tel' => '000-0000-0010',
                'email' => 'iguchi@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1500,
                'payment_method' => '1',
                'users_id' => 1,
                'name' => 'James Riney',
                'furigana' => 'ジェームズ ライニー',
                'email' => 'james_riney@coralcap.co',
                'tel' => '000-0000-0001',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1500,
                'payment_method' => '1',
                'users_id' => 1,
                'name' => 'James Riney',
                'furigana' => 'ジェームズ ライニー',
                'email' => 'james_riney@coralcap.co',
                'tel' => '000-0000-0001',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 200,
                'total_amount' => 1700,
                'payment_method' => '1',
                'users_id' => 1,
                'name' => 'James Riney',
                'furigana' => 'ジェームズ ライニー',
                'email' => 'james_riney@coralcap.co',
                'tel' => '000-0000-0001',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1250,
                'payment_method' => '1',
                'users_id' => 2,
                'name' => '澤山 陽平',
                'furigana' => 'サワヤマ ヨウヘイ',
                'tel' => '000-0000-0002',
                'email' => 'sawayama@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 200,
                'total_amount' => 1450,
                'payment_method' => '1',
                'users_id' => 2,
                'name' => '澤山 陽平',
                'furigana' => 'サワヤマ ヨウヘイ',
                'tel' => '000-0000-0002',
                'email' => 'sawayama@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 100,
                'total_amount' => 1024,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '吉澤 美弥子',
                'furigana' => 'ヨシザワ ミサコ',
                'tel' => '000-0000-0003',
                'email' => 'yoshizawa@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1724,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '津田 遼',
                'furigana' => 'ツダ リョウ',
                'tel' => '000-0000-0004',
                'email' => 'tsuda@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 864,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '小林 恭子',
                'furigana' => 'コバヤシ キョウコ',
                'tel' => '000-0000-0005',
                'email' => 'kobayashi@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1024,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '西村 賢',
                'furigana' => 'ニシムラ ケン',
                'tel' => '000-0000-0006',
                'email' => 'nishimura@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 768,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '大森 貴之',
                'furigana' => 'オオモリ タカユキ',
                'tel' => '000-0000-0007',
                'email' => 'oomori@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 886,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '小林 翔太郎',
                'furigana' => 'コバヤシ ショウタロウ',
                'tel' => '000-0000-0008',
                'email' => 's_kobayashi@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 1278,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '世古 圭',
                'furigana' => 'セコ ケイ',
                'tel' => '000-0000-0009',
                'email' => 'seko@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
            [
                'manages_id' => 1,
                'shops_id' => 1,
                'carts' => json_encode(['products_id' => 1]),
                'service' => 'お持ち帰り',
                'shipping' => 0,
                'delivery_time' => ''.date('Y-m-d H:i', rand($min, $max)).'',
                'okimochi' => 0,
                'total_amount' => 947,
                'payment_method' => '1',
                'users_id' => null,
                'name' => '井口 彰太',
                'furigana' => 'イグチ ショウタ',
                'tel' => '000-0000-0010',
                'email' => 'iguchi@coralcap.co',
                'created_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'updated_at' => date('Y-m-d H:i:s', rand($min, $max)),
                'cancel' => 0,
            ],
        ]);
    }
}
